version: "3.8"

services:
  redis:
    image: redis:7.0
    container_name: redis_container
    restart: unless-stopped
    command: redis-server --requirepass redispassword
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispassword
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  redis_data:
